# Generated by Django 5.1.4 on 2025-01-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_fees', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('PM', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('APM', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('FPPM', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Samvad_Donation', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Legal_Fund', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Misc_Donation', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('DRF', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Adv_Samvad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Interest_SB', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Interest_FD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Investments', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Guest_House_Receipt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Building_Fund', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Sundry_Receipt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Dividend', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Tds', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Tr_HQ', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Suspense', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
