# Generated by Django 5.1.4 on 2025-01-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlekhapal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='APM',
            new_name='apm_fees',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Building_Fund',
            new_name='building_fund',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='DRF',
            new_name='drf_fees',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='FPPM',
            new_name='fppm_fees',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Guest_House_Receipt',
            new_name='guest_house_receipt',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Interest_FD',
            new_name='interest_fd',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Interest_SB',
            new_name='interest_sb',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Investments',
            new_name='investments',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Legal_Fund',
            new_name='legal_fund',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Misc_Donation',
            new_name='misc_donation',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='PM',
            new_name='pm_fees',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Samvad_Donation',
            new_name='samvad_donation',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Sundry_Receipt',
            new_name='sundry_receipt',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Suspense',
            new_name='suspense',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Tds',
            new_name='tds_amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Total',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Tr_HQ',
            new_name='transfer_to_hq',
        ),
    ]
