# Generated by Django 5.1.4 on 2025-01-09 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlekhapal', '0002_rename_apm_payment_apm_fees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='zone',
            new_name='zone_name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Adv_Samvad',
            new_name='adv_samvad',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Dividend',
            new_name='dividend',
        ),
        migrations.AddField(
            model_name='login',
            name='zoneid',
            field=models.IntegerField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='chqno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='particulars',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='voucherno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='zoneid',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
